project:
  machine_name: d8alexmoreno.net
  prefix: BLT
  human_name: 'BLTed 8'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes:
    - 'alexmorenotest@svn-6634.devcloud.hosting.acquia.com:alexmorenotest.git'
drush:
  aliases:
    remote: alexmorenotest.test
    local: self
    ci: self
    test: alexmorenotest.test
    dev: alexmorenotest.dev
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: {  }
    uninstall: {  }
  ci:
    enable: {  }
    uninstall: {  }
  dev:
    enable: {  }
    uninstall: {  }
  test:
    enable: {  }
    uninstall: {  }
  prod:
    enable: {  }
    uninstall: {  }
cm:
  strategy: config-split
#  core:
#    path: ${repo.root}/config
#    key: sync
#    deploy-key: vcs
#    dirs:
#      sync:
#        path: ${cm.core.path}/default